import { DIRECT_RULES, PROXY_RULES, VPN_POLICY_DEFAULTS } from "./vpn-rules-data.js";

function sanitizePolicyName(name, fallback) {
  const value = name ?? fallback;
  if (!value || /[\r\n,]/.test(value)) {
    throw new Error("Policy names must not be empty or contain comma/newline characters");
  }
  return value;
}

export function parseVpnPolicyOptions(searchParams) {
  const proxy = sanitizePolicyName(searchParams.get("proxy"), VPN_POLICY_DEFAULTS.proxy);
  const direct = sanitizePolicyName(searchParams.get("direct"), VPN_POLICY_DEFAULTS.direct);
  const fallbackParam = searchParams.get("fallback");
  let fallback = proxy;

  if (fallbackParam) {
    const normalized = fallbackParam.toLowerCase();
    if (normalized === "proxy") {
      fallback = proxy;
    } else if (normalized === "direct") {
      fallback = direct;
    } else {
      fallback = sanitizePolicyName(fallbackParam, proxy);
    }
  }

  return { proxy, direct, fallback };
}

function rulesFromList(route, list) {
  return [
    ...(list.domainSuffixes ?? []).map((value) => ({ type: "DOMAIN-SUFFIX", value, route })),
    ...(list.domainKeywords ?? []).map((value) => ({ type: "DOMAIN-KEYWORD", value, route })),
    ...(list.domains ?? []).map((value) => ({ type: "DOMAIN", value, route })),
    ...(list.ipCidrs ?? []).map((value) => ({ type: "IP-CIDR", value, route, options: ["no-resolve"] })),
    ...(list.ipCidr6s ?? []).map((value) => ({ type: "IP-CIDR6", value, route, options: ["no-resolve"] })),
    ...(list.geoips ?? []).map((value) => ({ type: "GEOIP", value, route }))
  ];
}

export function getVpnRules() {
  return [
    ...rulesFromList("direct", DIRECT_RULES),
    ...rulesFromList("proxy", PROXY_RULES),
    { type: "MATCH", route: "fallback" }
  ];
}

function routePolicy(route, options) {
  if (route === "direct") {
    return options.direct;
  }
  if (route === "fallback") {
    return options.fallback;
  }
  return options.proxy;
}

export function formatClashRule(rule, options) {
  const policy = routePolicy(rule.route, options);
  if (rule.type === "MATCH") {
    return `MATCH,${policy}`;
  }

  const suffix = rule.options?.length ? `,${rule.options.join(",")}` : "";
  return `${rule.type},${rule.value},${policy}${suffix}`;
}

export function formatClashProviderRule(rule) {
  if (rule.type === "MATCH") {
    return null;
  }

  const suffix = rule.options?.length ? `,${rule.options.join(",")}` : "";
  return `${rule.type},${rule.value}${suffix}`;
}

function yamlLines(key, rules, options) {
  return [
    "# Generated by china-holidays Worker",
    `# proxy=${options.proxy} direct=${options.direct} fallback=${options.fallback}`,
    `${key}:`,
    ...rules.map((rule) => `  - ${formatClashRule(rule, options)}`)
  ];
}

export function createClashRulesYaml(options) {
  return `${yamlLines("rules", getVpnRules(), options).join("\n")}\n`;
}

export function createClashProviderYaml(route) {
  const rules = getVpnRules()
    .filter((rule) => rule.route === route)
    .map(formatClashProviderRule)
    .filter(Boolean);

  return [
    "# Generated by china-holidays Worker",
    `# route=${route}`,
    "payload:",
    ...rules.map((rule) => `  - ${rule}`)
  ].join("\n") + "\n";
}
